apiVersion: v1
kind: Secret
metadata:
  name: docu-mind-secrets
type: opaque
data:
  POSTGRES_PASSWORD: YWRtaW5fcGFzc3dvcmQ=
  GEMINI_API_KEY: QUl6YVN5Q2hZZFNNYmVGZFNONUN6NGhfQWUxblRlWV9uNnRPcTBr